# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Downward Spiral Chart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'Charts'
  use_frameworks!

  # Pods for Downward Spiral Chart

  target 'Downward Spiral ChartTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
